# -*- coding: utf-8 -*-
"""XGBoost.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16GUg5UM6Z3ApzdJi-QFQiZnwF2lcMX3y
"""

import xgboost as xgb
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

from google.colab import files
uploaded = files.upload()

import re
from urllib.parse import urlparse

def url_features(url):
    parsed = urlparse(url)
    return [
        len(url),
        url.count('.'),
        url.count('-'),
        url.count('@'),
        url.count('?'),
        url.count('='),
        int(parsed.scheme == 'https'),
        int(bool(re.search(r'\d+\.\d+\.\d+\.\d+', url)))
    ]

def html_features(url):
    try:
        response = requests.get(url, timeout=6)

        if response.text.strip().startswith("<?xml"):
            soup = BeautifulSoup(response.text, "xml")
        else:
            soup = BeautifulSoup(response.text, "html.parser")

        forms = len(soup.find_all('form'))
        iframes = len(soup.find_all('iframe'))
        scripts = len(soup.find_all('script'))

        external_links = 0
        for link in soup.find_all('a', href=True):
            if urlparse(link['href']).netloc not in ['', urlparse(url).netloc]:
                external_links += 1

        password_fields = len(
            soup.find_all('input', {'type': 'password'})
        )

        return [forms, iframes, scripts, external_links, password_fields]

    except:
        return [0, 0, 0, 0, 0]

def extract_features(url):
    return url_features(url)   # ❌ remove html_features while training

data = pd.read_csv("dataset_phishing.csv")

X = []
y = data['status']

for url in data['url']:
    X.append(extract_features(url))

X = np.array(X)

from sklearn.preprocessing import StandardScaler

# Standardize the features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

def predict_url(url):
    features = extract_features(url)
    prediction = model.predict(features)[0]
    probability = model.predict_proba(features)[0][prediction]

    if prediction == 1:
        return f"⚠️ PHISHING WEBSITE (Confidence: {probability:.2f})"
    else:
        return f"✅ LEGITIMATE WEBSITE (Confidence: {probability:.2f})"

from sklearn.preprocessing import LabelEncoder

# 1. Initialize the encoder
le = LabelEncoder()

# 2. Transform your labels
# This will turn 'legitimate' into 0 and 1 respectively.
y_train_encoded = le.fit_transform(y_train)
y_test_encoded = le.transform(y_test)

# Calculate scale_pos_weight using the encoded labels
# Assuming 'phishing' is the positive class (1) and 'legitimate' is the negative class (0)
positive_count = sum(y_train_encoded == 1)
negative_count = sum(y_train_encoded == 0)
scale_pos_weight_value = negative_count / positive_count

# Clean version - No more warnings
model = xgb.XGBClassifier(
    scale_pos_weight = scale_pos_weight_value,
    n_estimators=300,
    max_depth=8,
    learning_rate=0.05,
    subsample=0.9,
    colsample_bytree=0.9,
    eval_metric='logloss'
)



# Reshape X_train and X_test to 2D for XGBoost
X_train_reshaped = X_train.reshape(X_train.shape[0], -1)
X_test_reshaped = X_test.reshape(X_test.shape[0], -1)

# Ensure you use the encoded y values we discussed previously
model.fit(X_train_reshaped, y_train_encoded)

y_pred = model.predict(X_test_reshaped)
print(f"Accuracy: {accuracy_score(y_test_encoded, y_pred) * 100:.2f}%")

def predict_url(url):
    features = extract_features(url)
    prediction = model.predict(features)[0]
    probability = model.predict_proba(features)[0][prediction]

    if prediction == 1:
        return f"⚠️ PHISHING WEBSITE (Confidence: {probability:.2f})"
    else:
        return f"✅ LEGITIMATE WEBSITE (Confidence: {probability:.2f})"

print(predict_url("https://www.google.com"))
print(predict_url("https://www.amazon.in"))
print(predict_url("https://www.wikipedia.org"))

